# GitHub Pages Jekyll Configuration
title: Safelog.ai Documentation
description: Complete documentation for Safelog.ai background check integration
baseurl: "/docs-safelog.ai" # Repository name
url: "https://safelog-ai.github.io" # GitHub Pages URL

# Theme - using remote theme for better documentation
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Just the Docs theme configuration
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation footer
footer_content: "Copyright &copy; 2025 Safelog.ai. All rights reserved."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Site logo
logo: "/assets/images/safelog-logo.png"

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  integration:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_integration"
      type: "integration"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor